### ISSUE TITLE
会经常出现这样的问题

### ISSUE THREAD

**Issue by wuqiang-001** [koblas/pysnowflake#1]
![image](https://user-images.githubusercontent.com/85499933/174489431-29092d82-81cb-43df-8dd8-42c308a1ce7f.png)
![image](https://user-images.githubusercontent.com/85499933/174489434-5c613bd5-581b-4143-8610-4228aa9d14f1.png)

**Comment by koblas** [comment]
While the screen shots are interesting, can you please provide more specifics about how you ran both the client and server to demonstrate this.  The first screen shot is of tests

**Comment by wuqiang-001** [comment]
![image](https://user-images.githubusercontent.com/85499933/174508471-ff751578-f19b-41f9-a7ac-543e46fb8e5c.png)
![image](https://user-images.githubusercontent.com/85499933/174508513-76ac5ec0-4962-4925-b566-a481628fdf73.png)
![image](https://user-images.githubusercontent.com/85499933/174508599-b01528ab-3ff2-4e48-a6e5-beb75639c865.png)



1 pip install pysnowflake
2 snowflake_start_server
3 python test.py

**Comment by koblas** [comment]
Your screen shots indicate the the server started correctly and is listening on port 8910.  However no code or other information is provided for `snowflake.client` which is local code to your system or potentially a different package altogether.
